import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { useEffect } from 'react'
import { useRouter } from 'next/router'


export default function Home() {

  const router = useRouter();

  useEffect(() => {
    const interval = setInterval(() => {
      router.replace("/quizIntro")
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Borderless</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Image
          src={'/logo/borderless.svg'}
          alt={'borderless logo'}
          width={160}
          height={160}
        />
        <h3 className={styles.header}>Compassion knows no borders</h3>
      </main>
    </div>
  )
}
