import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/landingpage.module.css'
import Footer from '@/components/Footer'
import ImageSlider from '@/components/Carousel'

export default function LandingPage() {

    var title = process.env.NEXT_PUBLIC_HOME;


    return( 
        <div className={styles.container}>
            <Head>
                <title>Borderless</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           
            <main className={styles.main}>
            <div className={styles.title}>
                <img className={styles.homeicon} src='./icons/Bluehome.png'></img>
                <h1 className={styles.header}>{title}</h1>
            </div>
                <div className={styles.carousel}>
                <ImageSlider/>
                </div>
                <div className={styles.section2}>
                    <div className={styles.stats}>
                        <img className={styles.icon} src='./icons/graph.png'></img>
                        <a className={styles.name} href="stats">Empowering Through Data</a>
                        <p className={styles.stattext}>How you help Canada grow</p>
                    </div>
                    <div className={styles.resource}>
                        <img className={styles.icon2} src='./icons/heart.png'></img>
                        <a className={styles.name} href="resources">Local Support</a>
                        <p className={styles.stattext}>Find help in your area</p>
                    </div>
                </div>
                <div className={styles.section3}>
                    <div className={styles.weather}>
                        <img className={styles.icon} src='./icons/umbrella.png'></img>
                        <a className={styles.name} href="weather">Weather From Home</a>
                    </div>
                    <div className={styles.stories}>
                        <img className={styles.icon} src='./icons/dashboardstories.png'></img>
                        <a className={styles.name} href="stories">Stories of Hope and Help</a>
                    </div>
                </div>
                <Footer/>
            </main>

        </div>  
    )
}