import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/landingpage.module.css'
import Footer from '@/components/Footer'
import Link from 'next/link'
import ImageSlider from '@/components/Carousel'
import OntarioSlider from '@/components/OntarioCarousel'
import { useState } from 'react'
import { useEffect } from 'react'
export default function LandingPage() {

    var title = process.env.NEXT_PUBLIC_HOME;
    const [isProvince, setIsProvince] = useState(null);

    useEffect(() => {
      const province = localStorage.getItem('province');
      setIsProvince(province);
    }, []);

    console.log(isProvince);

    return( 
        <div className={styles.container}>
            <Head>
                <title>Borderless</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.profilesection}>
                    <Link href={'/settings'}>
                        <div className={styles.profile}>
                            <Image
                                src={'/icons/profile.png'}
                                height={40}
                                width={40}
                                alt={'profile'}    
                            />
                        </div>
                    </Link>
                    <div className={styles.title}>
                        <Image className={styles.homeicon} 
                            src={'/icons/Bluehome.png'}
                            height={60}
                            width={60}
                            alt={'home icon'}
                        />
                        <h1 className={styles.header}>{title}</h1>
                    </div>
                </div>
                <div className={styles.carousel}>
                    {
                        isProvince === 'British Columbia' && <ImageSlider/>
                    }
                    {
                        isProvince === 'Ontario' && <OntarioSlider/>
                    }
                </div>
                <div className={styles.section2}>
                    <Link href={"/statsDashboard"}><div className={styles.stats}>
                        <Image className={styles.icon} 
                            src={'/icons/graph.png'}
                            height={60}
                            width={60}
                            alt={'graph'}
                        />
                        <h3 className={styles.name}>Empowering Data</h3>
                        <p className={styles.stattext}>How you help Canada grow</p>
                    </div></Link>
                    <Link href={"/resources"}><div className={styles.resource}>
                        <Image className={styles.icon2} 
                            src={'/icons/heart.png'}
                            alt={'heart'}
                            height={60}
                            width={60}
                         />
                        <h3 className={styles.name}>Local Support</h3>
                        <p className={styles.stattext}>Find help in your area</p>
                    </div></Link>
                </div>
                <div className={styles.section3}>
                    <Link href={"/stories"}><div className={styles.stories}>
                        <Image className={styles.icon} 
                            src={'/icons/dashboardstories.png'}
                            height={60}
                            width={60}
                            alt={'stories'}
                        />
                        <h3 className={styles.name}>Stories of Hope</h3>
                    </div></Link>
                    <Link href={"/weather"}><div className={styles.weather}>
                        <Image className={styles.icon} 
                            src={'/icons/umbrella.png'}
                            height={60}
                            width={60}
                            alt={'umbrella'}
                        />
                        <h3 className={styles.name}>Weather From Home</h3>
                    </div></Link>
                </div>
                <Footer/>
            </main>
        </div>  
    )
}