import styles from '@/styles/QuizIntro.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import QuizButton from '@/components/QuizButton'
import SkipButton from '@/components/SkipButton'

export default function QuizIntro() {
    return (
        <div className={styles.container}>
          <Head>
            <title>Borderless</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <Image
              src={'/logo/borderless.svg'}
              alt={'borderless logo'}
              width={160}
              height={160}
            />
            <div className={styles.describer}>
              <p>Our quiz is designed to get to know you better so that we can provide you with personalized resources, stories, and statistics. </p>
              <p>By answering a few questions about your background and experiences, we can curate content to be tailored specifically to you. We believe that everyone's journey is unique, and our goal is to provide you with the tools and resources you need to make the most of your experience as a refugee in Canada.</p>
            </div>
            <QuizButton/> 
            <div className={styles.skip}>
            <Link href={'./landingpage'}><SkipButton/></Link>
            </div>
          </main>
        </div>
    )
}