import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/s4.module.css'
import Footer from '@/components/Footer'
import { storyData } from '@/data/organizationdata'
import { useState } from 'react'
import BackButton from '@/components/BackButton'
import Link from 'next/link'


export default function StoryFour() {

    const [information, setInformation] = useState([...storyData.gov]);

    return(
    
    <>
    <Head>
          <title>Borderless</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
    </Head>
    
<div className={styles.topsection}>
  <h1 className={styles.title}>Stories of Hope and Help</h1>
</div>
    
    <main className={styles.main}>
    
    
    <div>
            <div>
        
            {information && information.map((info, index) => {
              if(info.region === "Middle East"){
                return(
                <div className={styles.middleeast} key={index}>
    
              <Image
                src={info.image}
                height={186}
                width={364}
                alt={"pic"}
                />

             <div className={styles.header}>
                  {info.title}
            </div>

            <div className={styles.body}>
                  {info.body}
           </div>      
           <Link href={'./stories'}><BackButton/></Link>
                </div>
                )
              }
             })}
             </div>
             <div>
          
             {information && information.map((info, index) => {
              if(info.region === "Ukraine"){
                return(
    
                <div className={styles.ukraine}  key={index}>
                <Image
                src={info.image}
                height={186}
                width={364}
                alt={"picture"}
                />
                
                <div className={styles.header2}>
                   {info.title}
                </div>

                <div className={styles.body2}>
                   {info.body}
                </div>
                <Link href={'./stories'}><BackButton/></Link>
                   </div>
               
                )
              }
              })}
              </div>
       </div>
    
    
        </main>
        <Footer/>
      </>
    )
    }