import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/settings.module.css'
import Footer from '@/components/Footer'


export default function Settings() {


return (
        <>
        <Head>
            <title>Borderless - Settings</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <div className={styles.main}>
                <div className={styles.title}>
                    <h1>Settings</h1>
                    <Image
                        src={''}
                        alt={''}
                        width={157}
                        height={157}
                        className={styles.profilePic}
                    />
                    <h2>Hi Maria Duarte</h2>
                </div>
                <div className={styles.account}>
                    <div className={styles.icon}>
                        <Image
                            src={''}
                            alt={''}
                            width={30}
                            height={30}
                        />
                    </div>
                    <div className={styles.titles}>
                        <h3>Account</h3>
                        <p>Privacy, security, change email or phone number, language preferences</p>
                    </div>
                </div>
                <div className={styles.notifications}>
                    <div className={styles.icon}>
                        <Image
                            src={''}
                            alt={''}
                            width={25}
                            height={30}
                        />
                    </div>
                    <div className={styles.titles}>
                        <h3>Notifications</h3>
                        <p>Messages, tones</p>
                    </div>
                </div>
                <div className={styles.help}>
                    <div className={styles.icon}>
                        <Image
                            src={''}
                            alt={''}
                            width={30}
                            height={30}
                        />
                    </div>
                    <div className={styles.titles}>
                        <h3>Help</h3>
                        <p>Help center, contact us, privacy policy</p>
                    </div>
                </div>
                <div className={styles.colorMode}>
                    <div className={styles.icon}>
                        <Image
                            src={''}
                            alt={''}
                            width={30}
                            height={28}
                        />
                    </div>
                    <div className={styles.titles}>
                        <h3>Dark Mode/Light Mode</h3>
                    </div>
                </div>
                <div className={styles.faq}>
                    <div className={styles.icon}>
                        <Image
                            src={''}
                            alt={''}
                            width={30}
                            height={30}
                        />
                    </div>
                    <div className={styles.titles}>
                        <h3>FAQ</h3>
                    </div>
                </div>
            </div>
            <Footer/>
        </>
    )
}