import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/StatsDashboard.module.css'
import Footer from '@/components/Footer'
import Link from 'next/link'
import BackButton from '@/components/BackButton'

export default function StatsDashboard() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Borderless - Resources</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <div className={styles.titleSection}>
                    <Link href={'/landingpage'}><BackButton/></Link>
                    <h1 className={styles.header}>Empowering Data</h1>
                </div>
                <div className={styles.intro}>
                    <Image
                        src={'/images/workingTogether.jpg'}
                        alt={'learning together image'}
                        width={360}
                        height={220}
                        className={styles.introImage}
                    />
                    <div className={styles.introText}>
                        <h2 className={styles.subheader}>Empowering Through Data</h2>
                        <p>By sharing data that highlights positive experiences and success stories of other refugees in Canada, we hope to help to inspire hope and optimism among the community.</p>
                    </div>
                </div>
                <div className={styles.row}>
                    <Link href={'/stats'}><div className={styles.linkBox}>
                        <Image
                          src={'/icons/curated.svg'}
                          alt={'stats icon'}
                          width={54}
                          height={54}
                        />
                        <h3 className={styles.subheader}>Data For You</h3>
                    </div></Link>
                    <div className={styles.linkBox}>
                        <Image
                          src={'/icons/employment.svg'}
                          alt={'employment icon'}
                          width={54}
                          height={54}
                        />
                        <h3 className={styles.subheader}>Employment Rates</h3>
                    </div>
                </div>
                <div className={styles.row}>
                    <div className={styles.linkBox}>
                        <Image
                          src={'/icons/wellbeing.svg'}
                          alt={'wellbeing icon'}
                          width={54}
                          height={54}
                        />
                        <h3 className={styles.subheader}>Refugee Wellbeing</h3>
                    </div>
                    <div className={styles.linkBox}>
                        <Image
                          src={'/icons/community.svg'}
                          alt={'community icon'}
                          width={54}
                          height={54}
                        />
                        <h3 className={styles.subheader}>Sense of Belonging</h3>
                    </div>
                </div>
                <Footer/>
            </div>
        </div>
    )
}