import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/s2.module.css'
import Footer from '@/components/Footer'
import { storyData } from '@/data/organizationdata'
import { useState } from 'react'
import BackButton from '@/components/BackButton'
import Link from 'next/link'








export default function Stats() {
    return (

        <>
     <Head>
        <title>Borderless</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
      
      <main>





      </main>

        </>
    )
}