import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/stories.module.css'
import Footer from '@/components/Footer'
import ReadMore from '@/components/ReadMore'
import Link from 'next/link'
import BackButton from '@/components/BackButton'


export default function Stories() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Borderless</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.maincontent}>
                <div className={styles.top}>
                    <Link className={styles.BackButton} href={'./landingpage'}><BackButton/></Link>
                    <h1 className={styles.header}>Stories of Hope</h1>
                </div>
                <div className={styles.storycontent}>
                    <h2 className={styles.intro}>Learn how these organizations are making a difference in the lives of people from your home country.</h2>
                    <div className={styles.section1}>
                        <div className={styles.button1}>
                            <Link href={'/s1'}><Image
                                src={'/stories/unhcr.png'}
                                alt={'unhcr logo'}
                                width={201}
                                height={208}
                                className={styles.image1}
                            /></Link>
                            <Link href={'./s1'}><ReadMore/></Link> 
                        </div>
                        <div className={styles.button2}>
                            <Link href={'/s2'}><Image
                                src={'/stories/society.png'}
                                alt={'pacific immigrant resources society logo'}
                                width={140}
                                height={150}
                                className={styles.image3}
                            /></Link>
                            <Link href={'./s2'}><ReadMore/></Link> 
                        </div>    
                    </div>
                    <div className={styles.section2}>
                        <div className={styles.button3}>
                            <Link href={'/s3'}><Image
                                src={'/stories/redcross.png'}
                                alt={'canadian red cross logo'}
                                width={208}
                                height={201}
                                className={styles.image2}
                            /></Link>
                            <Link href={'./s3'}><ReadMore/></Link> 
                        </div>
                        <div className={styles.button4}>
                            <Link href={'/s4'}><Image
                                src={'/stories/government.png'}
                                alt={'government of canada logo'}
                                width={140}
                                height={150}
                                className={styles.image4}
                            /></Link>
                            <Link href={'./s4'}><ReadMore/></Link> 
                        </div>
                    </div>
                </div>
                <Footer/>
            </main>
        </div>
    )
}