import styles from '@/styles/Weather.module.css'
import Head from 'next/head'
import Image from 'next/image'
import Footer from '@/components/Footer'
import Link from 'next/link'
import BackButton from '@/components/BackButton'

export default function Weather() {
    return (
    <div className={styles.container}>

<Head>
        <title>Borderless</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
</Head>

    
    
    


<main className={styles.maincontent}>
<div className={styles.top}>
    <Link href={'./landingpage'}><BackButton/></Link>
    <h1 className={styles.weather}>Weather</h1>
</div>

        
        
        
<div className={styles.mapsection}>
    <h1 className={styles.title}>Eastern Europe radar map</h1>
        <Image
           className={styles.image}
           src={"/images/map.png"}
           alt={'map'}
           width={358}
           height={310}
        />
    
    <h1 className={styles.title2}>Eastern Europe weather conditions</h1>


    <div className={styles.locations}>
     
     <div className={styles.weather1}>
    <h3 className={styles.location1}>Budapest</h3>
    <Image
        src={'/icons/cloudy.png'}
        alt={'cloud'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>21</p>
    </div>
    <div className={styles.weather1}>
    <h3 className={styles.location1}>Tallin</h3>
    <Image
        src={'/icons/cloudy.png'}
        alt={'cloud'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>25</p>
    </div>
    </div>
    <div className={styles.locations}>
     
     <div className={styles.weather1}>
    <h3 className={styles.location1}>Kyiv</h3>
    <Image
        src={'/icons/sunny.png'}
        alt={'sun'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>30</p>
    </div>
    <div className={styles.weather1}>
    <h3 className={styles.location1}>Bucharest</h3>
    <Image
        src={'/icons/cloudy.png'}
        alt={'cloud'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>18</p>
    </div>
  
   </div>
   <div className={styles.locations}>
     
     <div className={styles.weather1}>
    <h3 className={styles.location1}>St Petersburg</h3>
    <Image
        src={'/icons/lightning.png'}
        alt={'rain'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>21</p>
    </div>
    <div className={styles.weather1}>
    <h3 className={styles.location1}>Warsaw</h3>
    <Image
        src={'/icons/sunny.png'}
        alt={'sun'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>26</p>
    </div>
  
   </div>
   <div className={styles.locations}>
     
     <div className={styles.weather1}>
    <h3 className={styles.location1}>Prague</h3>
    <Image
        src={'/icons/sunny.png'}
        alt={'sun'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>27</p>
    </div>
    <div className={styles.weather1}>
    <h3 className={styles.location1}>Sofia</h3>
    <Image
        src={'/icons/cloudy.png'}
        alt={'cloud'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>21</p>
    </div>
  
   </div>
   <div className={styles.locations}>
     
     <div className={styles.weather1}>
    <h3 className={styles.location1}>Moscow</h3>
    <Image
        src={'/icons/cloudy.png'}
        alt={'sun'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>22</p>
    </div>
    <div className={styles.weather1}>
    <h3 className={styles.location1}>Plovdiv</h3>
    <Image
        src={'/icons/sunny.png'}
        alt={'sun'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>25</p>
    </div>
  
   </div>
   <div className={styles.locations}>
     
     <div className={styles.weather1}>
    <h3 className={styles.location1}>Riga</h3>
    <Image
        src={'/icons/sunny.png'}
        alt={'sun'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>29</p>
    </div>
    <div className={styles.weather1}>
    <h3 className={styles.location1}>Kraków</h3>
    <Image
        src={'/icons/lightning.png'}
        alt={'storm'}
        width={18}
        height={18}
        className={styles.icon}
        />
        <p>27</p>
    </div>
  
   </div>
  
  
 
</div>


    </main>
    
    <Footer/>
    
    </div>
    )
}
    
    
    
    
